"""Game-neutral Sim Pilot Game Bridge Protocol v2."""

from sim_pilot.game_bridge.client import ClientState, GameBridgeClient, GameBridgeConfiguration
from sim_pilot.game_bridge.errors import (
    GameBridgeAuthenticationError,
    GameBridgeConnectionError,
    GameBridgeError,
    GameBridgeIncompatibleError,
    GameBridgeMessageSizeError,
    GameBridgeProtocolError,
    GameBridgeSequenceError,
    GameBridgeSnapshotError,
    GameBridgeTimeoutError,
)
from sim_pilot.game_bridge.models import (
    DEFAULT_MAXIMUM_MESSAGE_BYTES,
    PROTOCOL_VERSION,
    Architecture,
    BridgeEnvelope,
    CapabilityManifestPayload,
    CoverageStatus,
    FieldCoverage,
    GameSnapshot,
    Identity,
    IdentityStatus,
    MessageType,
    ObservationSurface,
    ObservedEntity,
    Platform,
    SetRouteResponsePayload,
    parse_envelope,
)

__all__ = [
    "DEFAULT_MAXIMUM_MESSAGE_BYTES",
    "PROTOCOL_VERSION",
    "Architecture",
    "BridgeEnvelope",
    "CapabilityManifestPayload",
    "ClientState",
    "CoverageStatus",
    "FieldCoverage",
    "GameBridgeAuthenticationError",
    "GameBridgeClient",
    "GameBridgeConfiguration",
    "GameBridgeConnectionError",
    "GameBridgeError",
    "GameBridgeIncompatibleError",
    "GameBridgeMessageSizeError",
    "GameBridgeProtocolError",
    "GameBridgeSequenceError",
    "GameBridgeSnapshotError",
    "GameBridgeTimeoutError",
    "GameSnapshot",
    "Identity",
    "IdentityStatus",
    "MessageType",
    "ObservationSurface",
    "ObservedEntity",
    "Platform",
    "SetRouteResponsePayload",
    "parse_envelope",
]
